spring:
  application:
    name: spring-cloud-config-server
server:
  port: 80
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,bus-refresh"
--- #Kubernetes
spring:
  config:
    activate:
      on-profile: kubernetes
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: main
          clone-on-start: true
          skipSslValidation: true
          timeout: 30
