apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: config-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: config-server
        app: config-server
    spec:
      containers:
        - name: config-server
          image: docker.io/lazycomputing/config-server
          envFrom:
            - configMapRef:
                name: config-server-specifications
          ports:
            - containerPort: 8080
              name: service
            - containerPort: 8081
              name: management
          resources: {}
      restartPolicy: Always