name: Build Maven Project

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
env:
  REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
  USERNAME: ${{ vars.DOCKER_HUB_USERNAME }}
  PACKAGE: ${{ vars.PACKAGE_NAME }}

jobs:
  config:
    uses: digilinq/reusable-workflows/.github/workflows/project-configuration.yaml@v0.0.13-beta

  diag:
    name: diag
    needs:
      - config
    runs-on: ubuntu-latest
    steps:
      - run: echo kubernetes namespace ${{ needs.config.outputs.kubernetes-namespace }}
      - run: echo deployment ${{ needs.config.outputs.deployment }}
      - run: echo deployment.namespace ${{ fromJSON(needs.config.outputs.deployment-json-object).namespace }}

  build:
    name: build
    needs:
      - config
    uses: digilinq/reusable-workflows/.github/workflows/build-maven-project.yaml@v0.0.13-beta
    with:
      runner: 'ubuntu-latest'
      ref: ${{ github.ref }}
      java-version: ${{ needs.config.outputs.java-version }}
      maven-version: ${{ needs.config.outputs.maven-version }}
      artifact-name: 'Package'
      artifact-path: 'target/*.jar'
      docker-file: 'Dockerfile'

  docker-container-registry:
    name: image-specifications
    uses: digilinq/reusable-workflows/.github/workflows/docker-image-specifications.yaml@v0.0.13-beta
    with:
      registry: ${{ vars.CONTAINER_REGISTRY }}
      namespace: ${{ vars.DOCKER_HUB_USERNAME }}
      repository: ${{ vars.PACKAGE_NAME }}

  create-docker-image:
    name: Create docker image
    needs:
      - config
      - build
      - docker-container-registry
    uses: digilinq/reusable-workflows/.github/workflows/create-docker-image.yaml@v0.0.13-beta
    with:
      runner: 'ubuntu-latest'
      artifact-name: 'Package'
      docker-image: ${{ needs.docker-container-registry.outputs.docker }}
    secrets:
      container-registry-password: ${{ secrets.DOCKER_HUB_PASSWORD }}

  deploy:
    name: Deploy
    needs:
      - config
      - create-docker-image
    uses: digilinq/reusable-workflows/.github/workflows/kubernetes-deploy.yaml@v0.0.13-beta
    with:
      runner: 'ubuntu-latest'
      ref: ${{ github.ref }}
      image: ${{ needs.create-docker-image.outputs.docker-image }}
      namespace: 'tech-innovative'
    secrets:
      kubernetes-url: ${{ secrets.KUBERNETES_URL }}
      kubernetes-secret: ${{ secrets.KUBERNETES_SECRET }}
